### ISSUE TITLE
Weird behavior file size

### ISSUE THREAD

**Issue by damienlethiec** [alexharris/ditherit-v2#1]
Hi there,

Thanks for the awesome tool ! Super cool !

There are only 2 things I don't understand and want to clarify :
- Why is the filesize larger than the original when we select the original image size ?
![image](https://user-images.githubusercontent.com/8105430/71410990-cea9f600-2647-11ea-9bea-e9da7bc92053.png)
- Why is the filesize larger when we select the origin color palette than when we use black and white ?
![image](https://user-images.githubusercontent.com/8105430/71411013-e08b9900-2647-11ea-865f-7da397656a94.png)
![image](https://user-images.githubusercontent.com/8105430/71411026-f26d3c00-2647-11ea-9f14-68622480e10b.png)

Also, would it b possible to dither several images at once?

Thanks so much,
Damien

**Comment by alexharris** [comment]
Hello @damienlethiec,
Thanks for using Dither it! Glad that you are finding it helpful.

Disclaimer: I do not know a whole heck of a lot about compression.

**Issue 1:** If the original sized dithered image is larger than the original non-dithered image, this could be because the image you are uploading has been compressed. Dither it! does not do any image compression on the output, it just puts each individual pixel in order. So if you are uploading an image that has any sort of compression, the non-compressed output of Dither it! will almost always be larger. If you are using these images for the web, I would recommend re-compressing them after dithering.

**Issue 2:** I'm not exactly sure what is going on here. I would expect them to be the same size. I just did a little testing and a four color dither is between the original 8 color and the black and white, so it seems that there is some correlation between number of colors and file size. Upon doing a little reading, it might be related to how JPG encoding deals with color bits vs black and white bits..or something like this. I should look into this more! It also seems I might be encoding the PNGs a little bit incorrectly. So I need to do a little work here. Thanks for bringing this to my attention.

Also, if you are using Dither it! for a website or online project, I'd love to see the result!

thanks,
Alex

**Comment by alexharris** [comment]
oh yeah also @damienlethiec I do hope to add ability to dither multiple images at once!

**Comment by damienlethiec** [comment]
Thanks so much of the answer @alexharris !

Issue 1: I tried with an image that is not compress (100% sure) and I weirdly got the same result :/ I don't get why

Issue 2: Intuitively, I would also believe using 2 colors would be smaller than using 4 which would be smaller than using 8 but the contrary is happening every time apparently.

A bit more investigation needed apparently ;)

Anyway, thanks so much for the great work already. It is a great idea ! Super inspiring ! I will indeed probably use it for some projects. If I find time, I will also probably try to package the same features in a jekyll gem. It would be super useful for a lot of projects.

P.S: Is there any reason why you do not want to do the compression in the tool?

Thanks again and merry christmas !

**Comment by alexharris** [comment]
@damienlethiec 

Okay, yeah I will look into all of that. 

The reason I do not do compression in the tool is...it seems complicated! First of all, Dither it! uses no server or serverless technology, it is all in the browser, which makes it cheap and easy to run. Maybe there are some javascript libraries that do image compression? Not really sure, I mostly known ImageMagick, which needs to run on a server. I could look into that, but in terms of just getting Dither it! up and running, I excluded this. Since it turns out people some to actually like and use this tool, I will start thinking about some more advanced features (multiple images, better compression, more options, etc).

I think a Jekyll gem would be really cool, probably you just want to use the quantization library at https://github.com/leeoniya/RgbQuant.js which is what Dither it! uses under the hood as well. Keep me posted if that progresses!

**Comment by alexharris** [comment]
@damienlethiec quick google reveals quite a few JS image compression libraries! OK, this is now on the to do list :)

**Comment by damienlethiec** [comment]
You rock ;)

**Comment by alexharris** [comment]
@damienlethiec While I did not implement any sort of compression, I do believe I fixed a bug that was confusing forcing all images to save as JPG, which was messing with filesizes..do you mind trying your images again to see if there is a better outcome?

**Comment by damienlethiec** [comment]
@alexharris  thanks so much :)

It is getting closer ! But the more color we keep, the smaller the file still is (8 colors is smaller than 4, which is smaller than 2). And while 8 colors dithers are now smaller than the original image for the same size, black and white dithers are still bigger.

Thanks so much again :)

**Comment by alexharris** [comment]
@damienlethiec ok great. yeah i havent gotten into the color stuff yet, just hoping that the overall filesizes are now smaller than they had been. more to come

**Comment by alexharris** [comment]
@damienlethiec yo! I got a beta version of multi-image functionality. I'd appreciate any feedback you have or bugs you find, if you want to take it for a spin: https://sad-dubinsky-a92d9c.netlify.com/

thanks,
Alex

**Comment by damienlethiec** [comment]
@alexharris thanks a ton :) It is super slow (navigating between images for example) but it seems to work well ;)

**Comment by alexharris** [comment]
Cool. How big are the images you are using and how many at a time?

**Comment by damienlethiec** [comment]
2 of around 4mo

**Comment by alexharris** [comment]
4mb?

That’s pretty big for the web so I’m not surprised it is Slow. Maybe I can
display only up to a certain size to keep it faster...

**Comment by alexharris** [comment]
@damienlethiec ok, I moved the code to the main site! thanks again for all the feedback
