### ISSUE TITLE
Ignore transparent pixels when dithering

### ISSUE THREAD

**Issue by Krasjet** [alexharris/ditherit-v2#34]
The current algorithm seems to treat transparent background as black. This is quite annoying when dealing with png images. I wonder if there is a option to reset all the transparent pixels in the input image to transparent in the output?

**Comment by Krasjet** [comment]
probably related to https://github.com/leeoniya/RgbQuant.js/issues/7

**Comment by alexharris** [comment]
Hi thanks for submitting this! This does seem like something obvious to resolve, maybe the RGBquant fork that is mentioned in that issue is something I should look into.

**Comment by Krasjet** [comment]
I think an easy solution could be just adding an option to copying the alpha channel from the input to the output, not sure how well it optimizes the size, but it can be optimized later using optipng or something.

**Comment by alexharris** [comment]
that could work. I'll give it a try when i've got time!

**Comment by alexharris** [comment]
I started to look into this, and I will just note that the Bayer (Ordered) dither mode does support transparency.

**Comment by alexharris** [comment]
Worked on this a little more and it seems that it is too intensive to copy the alpha value of every pixel on the original image, and move that to the output, at least as far as I know how to do it. Using a simple for loop, I tried to copy the alpha values of a relatively small (500x400ish) image, and just that alone crashed the browser tab as it has to iterate through over a million RGBA values. 

Maybe there is a more performant way to do it?

Also, [this stack overflow](https://stackoverflow.com/questions/11611549/transparent-pixels-using-html5-canvas-and-getimagedata) is pretty interesting, it covers how to preserve transparency when copy a png to a canvas, which is what we are doing, but the problem is that rgbquant needs to do its thing on the image data, and so there is no way to not lose the alpha values from what I can tell.

This all continues to point towards needing to fix the issuein RGBQuant, or switch to the potentially more modern rgbquant alternative: https://github.com/ibezkrovnyi/image-quantization

**Comment by alexharris** [comment]
OK I did finally resolve this issue using @Krasjet suggestion:

> I think an easy solution could be just adding an option to copy the alpha channel from the input to the output, not sure how well it optimizes the size, but it can be optimized later using optipng or something.

I forked RGBQuant.js and added code to track the transparent pixels, and then re-transparent them after the dither. Seems to work fine? Havent tested anything about how it affects speed or size, but it seems fine for now.
